<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Proyecto_Final_POO_C_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Cliente.cs" />
    <Compile Remove="Proyecto_Final_POO_C_.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Proyecto_Final_POO_C_.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Source\Escritores\" />
  </ItemGroup>

</Project>
